package make

var Postgresql = Database{
	Name: "postgres",
	Fields: []Field{
		{Tag: "bigint", Array: true, Default: "int64", Accept: []string{"int*", "uint*"}, Reject: []string{"float*", "string"}},
		{Tag: "int8", Array: true, Default: "int8", Accept: []string{}, Reject: []string{}},
		{Tag: "bigserial", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "serial8", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "bit", Array: true, Default: "byte", Accept: []string{}, Reject: []string{}},
		{Tag: "bit_varying", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "boolean", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "bool", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "box", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "bytea", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "character", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "char", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "character_varying", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "varchar", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "cidr", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "circle", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "date", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "double_precision", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "float8", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "inet", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "integer", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "int", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "int4", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "interval", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "json", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "jsonb", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "line", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "lseg", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "macaddr", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "macaddr8", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "money", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "numeric", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "decimal", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "path", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "pg_lsn", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "pg_snapshot", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "point", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "polygon", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "real", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "float4", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "smallint", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "int2", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "smallserial", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "serial2", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "serial", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "serial4", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "text", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "time", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "time_with_timezone", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "timez", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "timestamp", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "timestamp_with_timezone", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "timestampz", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "tsquery", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "tsvector", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "txid_snapshot", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "uuid", Array: true, Default: "int64", Accept: []string{}, Reject: []string{}},
		{Tag: "xml", Array: true, Default: "string", Accept: []string{}, Reject: []string{}},
	},
}
