package postgresql

import (
	"context"
	"database/sql"
	"github.com/shopspring/decimal"
	"time"
)

type TestMapper struct {
	SelectInsert                     func(entity Entity) (id int, err error)
	SelectInsertPointer              func(entity *EntityPointer) (id int32, err error)
	SelectInsertForeachSlice         func(testEntity Entity, enums []string) (id int16, err error)
	SelectInsertForeachSlicePointer  func(testEntity *EntityPointer, enums *[][]*string) (id int32, err error)
	SelectInsertForeachMap           func(testEntity Entity, enums map[string][]string) (id uint, err error)
	SelectInsertForeachMapPointer    func(testEntity *EntityPointer, enums *map[string][]*string) (id uint16, err error)
	SelectInsertForeachStruct        func(testEntity Entity) (id uint32, err error)
	SelectInsertForeachStructPointer func(testEntity *EntityPointer) (id uint64, err error)
	SelectInsertContextTx            func(ctx context.Context, tx *sql.Tx, testEntity Entity) (int int, err error)
	Insert                           func(name string, tags ...string) (rows int64, err error)
	SelectRow                        func(id int) (t_char, t_text string, err error)
	SelectRowPointer                 func(id *int) (t_char, t_text *string, err error)
	SelectRows                       func(start, end int) (t_char []string, t_text []sql.NullString, err error)
	SelectRowsPointer                func(start, end *int) (t_char, t_text []*string, err error)
	SelectStruct                     func(id int) (entity Entity, err error)
	SelectStructPointer              func(id int) (entity *Entity, err error)
	SelectStructs                    func(id int) (entity []Entity, err error)
	SelectStructsPointer             func(id int) (entity []*Entity, err error)
}

type StmtMapper struct {
	TestInsertStmt    func(user *User) error
	TestInsertStmt2   func(user *User) error
	TestQueryStmt     func(name string, age int64) ([]*User, error)
	TestQueryStmt2    func(name string, age int64) ([]*User, error)
	InsertStringArray func(user *User) (err error)
	GetStringArray    func(name string) (user *User, err error)
}

type InsertMapper struct {
	InsertR001 func(member *Member) (err error)
	InsertR002 func(member *Member) (id int64, err error)
	InsertR011 func(member *Member) (err error)
	InsertR012 func(member *Member) (id int64, err error)
}

type QueryMapper struct {
	QueryR001 func(page, limit, status int64) (count int64, members []*Member, err error)
}

func NewMapper() *Mapper {
	return &Mapper{
		&insertMapper{},
	}
}

type Mapper struct {
	*insertMapper
}

type insertMapper struct {
	InsertTBigint                func(value int64) (int, error)
	InsertTInt8                  func(value int64) (int, error)
	InsertTBigserial             func(value int8) (int, error)
	InsertTSerial8               func(value int64) (int, error)
	InsertTBit                   func(value int64) (int, error)
	InsertTBitVarying            func(value byte) (int, error)
	InsertTBoolean               func(value byte) (int, error)
	InsertTBool                  func(value bool) (int, error)
	InsertTBox                   func(value bool) (int, error)
	InsertTBytea                 func(value string) (int, error)
	InsertTCharacter             func(value byte) (int, error)
	InsertTChar                  func(value string) (int, error)
	InsertTCharacterVarying      func(value string) (int, error)
	InsertTVarchar               func(value string) (int, error)
	InsertTCidr                  func(value string) (int, error)
	InsertTCircle                func(value string) (int, error)
	InsertTDate                  func(value string) (int, error)
	InsertTDoublePrecision       func(value time.Time) (int, error)
	InsertTFloat8                func(value float64) (int, error)
	InsertTInet                  func(value float32) (int, error)
	InsertTInteger               func(value string) (int, error)
	InsertTInt                   func(value int) (int, error)
	InsertTInt4                  func(value int) (int, error)
	InsertTInterval              func(value int8) (int, error)
	InsertTJson                  func(value time.Duration) (int, error)
	InsertTJsonb                 func(value string) (int, error)
	InsertTLine                  func(value string) (int, error)
	InsertTLseg                  func(value int) (int, error)
	InsertTMacaddr               func(value int) (int, error)
	InsertTMacaddr8              func(value string) (int, error)
	InsertTMoney                 func(value string) (int, error)
	InsertTNumeric               func(value decimal.Decimal) (int, error)
	InsertTDecimal               func(value decimal.Decimal) (int, error)
	InsertTPath                  func(value decimal.Decimal) (int, error)
	InsertTPgLsn                 func(value int) (int, error)
	InsertTPgSnapshot            func(value int) (int, error)
	InsertTPoint                 func(value int) (int, error)
	InsertTPolygon               func(value int) (int, error)
	InsertTReal                  func(value int) (int, error)
	InsertTFloat4                func(value int) (int, error)
	InsertTSmallint              func(value int) (int, error)
	InsertTInt2                  func(value int) (int, error)
	InsertTSmallserial           func(value int) (int, error)
	InsertTSerial2               func(value int) (int, error)
	InsertTSerial                func(value int) (int, error)
	InsertTSerial4               func(value int) (int, error)
	InsertTText                  func(value int) (int, error)
	InsertTTime                  func(value string) (int, error)
	InsertTTimeWithTimezone      func(value time.Time) (int, error)
	InsertTTimez                 func(value time.Time) (int, error)
	InsertTTimestamp             func(value time.Time) (int, error)
	InsertTTimestampWithTimezone func(value time.Time) (int, error)
	InsertTTimestampz            func(value time.Time) (int, error)
	InsertTTsquery               func(value time.Time) (int, error)
	InsertTTsvector              func(value int8) (int, error)
	InsertTTxidSnapshot          func(value int8) (int, error)
	InsertTUuid                  func(value int8) (int, error)
	InsertTXml                   func(value string) (int, error)
}

type updateMapper struct {
	UpdateTBigint                func(id int, value int64) (int, error)
	UpdateTInt8                  func(id int, value int64) (int, error)
	UpdateTBigserial             func(id int, value int8) (int, error)
	UpdateTSerial8               func(id int, value int64) (int, error)
	UpdateTBit                   func(id int, value int64) (int, error)
	UpdateTBitVarying            func(id int, value byte) (int, error)
	UpdateTBoolean               func(id int, value byte) (int, error)
	UpdateTBool                  func(id int, value bool) (int, error)
	UpdateTBox                   func(id int, value bool) (int, error)
	UpdateTBytea                 func(id int, value string) (int, error)
	UpdateTCharacter             func(id int, value byte) (int, error)
	UpdateTChar                  func(id int, value string) (int, error)
	UpdateTCharacterVarying      func(id int, value string) (int, error)
	UpdateTVarchar               func(id int, value string) (int, error)
	UpdateTCidr                  func(id int, value string) (int, error)
	UpdateTCircle                func(id int, value string) (int, error)
	UpdateTDate                  func(id int, value string) (int, error)
	UpdateTDoublePrecision       func(id int, value time.Time) (int, error)
	UpdateTFloat8                func(id int, value float64) (int, error)
	UpdateTInet                  func(id int, value float32) (int, error)
	UpdateTInteger               func(id int, value string) (int, error)
	UpdateTInt                   func(id int, value int) (int, error)
	UpdateTInt4                  func(id int, value int) (int, error)
	UpdateTInterval              func(id int, value int8) (int, error)
	UpdateTJson                  func(id int, value time.Duration) (int, error)
	UpdateTJsonb                 func(id int, value string) (int, error)
	UpdateTLine                  func(id int, value string) (int, error)
	UpdateTLseg                  func(id int, value int) (int, error)
	UpdateTMacaddr               func(id int, value int) (int, error)
	UpdateTMacaddr8              func(id int, value string) (int, error)
	UpdateTMoney                 func(id int, value string) (int, error)
	UpdateTNumeric               func(id int, value decimal.Decimal) (int, error)
	UpdateTDecimal               func(id int, value decimal.Decimal) (int, error)
	UpdateTPath                  func(id int, value decimal.Decimal) (int, error)
	UpdateTPgLsn                 func(id int, value int) (int, error)
	UpdateTPgSnapshot            func(id int, value int) (int, error)
	UpdateTPoint                 func(id int, value int) (int, error)
	UpdateTPolygon               func(id int, value int) (int, error)
	UpdateTReal                  func(id int, value int) (int, error)
	UpdateTFloat4                func(id int, value int) (int, error)
	UpdateTSmallint              func(id int, value int) (int, error)
	UpdateTInt2                  func(id int, value int) (int, error)
	UpdateTSmallserial           func(id int, value int) (int, error)
	UpdateTSerial2               func(id int, value int) (int, error)
	UpdateTSerial                func(id int, value int) (int, error)
	UpdateTSerial4               func(id int, value int) (int, error)
	UpdateTText                  func(id int, value int) (int, error)
	UpdateTTime                  func(id int, value string) (int, error)
	UpdateTTimeWithTimezone      func(id int, value time.Time) (int, error)
	UpdateTTimez                 func(id int, value time.Time) (int, error)
	UpdateTTimestamp             func(id int, value time.Time) (int, error)
	UpdateTTimestampWithTimezone func(id int, value time.Time) (int, error)
	UpdateTTimestampz            func(id int, value time.Time) (int, error)
	UpdateTTsquery               func(id int, value time.Time) (int, error)
	UpdateTTsvector              func(id int, value int8) (int, error)
	UpdateTTxidSnapshot          func(id int, value int8) (int, error)
	UpdateTUuid                  func(id int, value int8) (int, error)
	UpdateTXml                   func(id int, value string) (int, error)
}

type selectMapper struct {
	SelectTBigint                func(id int) (int64, error)
	SelectTInt8                  func(id int) (int64, error)
	SelectTBigserial             func(id int) (int8, error)
	SelectTSerial8               func(id int) (int64, error)
	SelectTBit                   func(id int) (int64, error)
	SelectTBitVarying            func(id int) (byte, error)
	SelectTBoolean               func(id int) (byte, error)
	SelectTBool                  func(id int) (bool, error)
	SelectTBox                   func(id int) (bool, error)
	SelectTBytea                 func(id int) (string, error)
	SelectTCharacter             func(id int) (byte, error)
	SelectTChar                  func(id int) (string, error)
	SelectTCharacterVarying      func(id int) (string, error)
	SelectTVarchar               func(id int) (string, error)
	SelectTCidr                  func(id int) (string, error)
	SelectTCircle                func(id int) (string, error)
	SelectTDate                  func(id int) (string, error)
	SelectTDoublePrecision       func(id int) (time.Time, error)
	SelectTFloat8                func(id int) (float64, error)
	SelectTInet                  func(id int) (float32, error)
	SelectTInteger               func(id int) (string, error)
	SelectTInt                   func(id int) (int, error)
	SelectTInt4                  func(id int) (int, error)
	SelectTInterval              func(id int) (int8, error)
	SelectTJson                  func(id int) (time.Duration, error)
	SelectTJsonb                 func(id int) (string, error)
	SelectTLine                  func(id int) (string, error)
	SelectTLseg                  func(id int) (int, error)
	SelectTMacaddr               func(id int) (int, error)
	SelectTMacaddr8              func(id int) (string, error)
	SelectTMoney                 func(id int) (string, error)
	SelectTNumeric               func(id int) (decimal.Decimal, error)
	SelectTDecimal               func(id int) (decimal.Decimal, error)
	SelectTPath                  func(id int) (decimal.Decimal, error)
	SelectTPgLsn                 func(id int) (int, error)
	SelectTPgSnapshot            func(id int) (int, error)
	SelectTPoint                 func(id int) (int, error)
	SelectTPolygon               func(id int) (int, error)
	SelectTReal                  func(id int) (int, error)
	SelectTFloat4                func(id int) (int, error)
	SelectTSmallint              func(id int) (int, error)
	SelectTInt2                  func(id int) (int, error)
	SelectTSmallserial           func(id int) (int, error)
	SelectTSerial2               func(id int) (int, error)
	SelectTSerial                func(id int) (int, error)
	SelectTSerial4               func(id int) (int, error)
	SelectTText                  func(id int) (int, error)
	SelectTTime                  func(id int) (string, error)
	SelectTTimeWithTimezone      func(id int) (time.Time, error)
	SelectTTimez                 func(id int) (time.Time, error)
	SelectTTimestamp             func(id int) (time.Time, error)
	SelectTTimestampWithTimezone func(id int) (time.Time, error)
	SelectTTimestampz            func(id int) (time.Time, error)
	SelectTTsquery               func(id int) (time.Time, error)
	SelectTTsvector              func(id int) (int8, error)
	SelectTTxidSnapshot          func(id int) (int8, error)
	SelectTUuid                  func(id int) (int8, error)
	SelectTXml                   func(id int) (string, error)
}
