package postgresql

import (

    "database/sql"
    "github.com/gobatis/gobatis"
    "context"
)

type MakeMapper struct {

    InsertParameterBigintInt64 func( var_bigint int64, )(  error, )
    InsertParameterBigintInt64PointerOriginal func( var_bigint int64, )(  error, )
    InsertEntityBigintInt64 func( var_bigint int64, )(  error, )
    InsertEntityBigintInt64PointerOriginal func( var_bigint *int64, )(  error, )
    InsertParameterBigintInt64Tx func( tx sql.Tx,  var_bigint int64, )(  error, )
    InsertParameterBigintInt64Rows func( var_bigint int64, )(  int,   error, )
    InsertParameterBigintInt64Context func( ctx context.Context,  var_bigint int64, )(  error, )
    InsertParameterBigintInt64Stmt func( var_bigint int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBigintInt64Must func( var_bigint int64, )(  error, )
    InsertParameterBigintInt64Embed func( var_bigint int64, )(  error, )
    InsertParameterInt8Int8 func( var_int8 int8, )(  error, )
    InsertParameterInt8Int8PointerOriginal func( var_int8 int8, )(  error, )
    InsertEntityInt8Int8 func( var_int8 int8, )(  error, )
    InsertEntityInt8Int8PointerOriginal func( var_int8 *int8, )(  error, )
    InsertParameterInt8Int8Tx func( tx sql.Tx,  var_int8 int8, )(  error, )
    InsertParameterInt8Int8Rows func( var_int8 int8, )(  int,   error, )
    InsertParameterInt8Int8Context func( ctx context.Context,  var_int8 int8, )(  error, )
    InsertParameterInt8Int8Stmt func( var_int8 int8, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterInt8Int8Must func( var_int8 int8, )(  error, )
    InsertParameterInt8Int8Embed func( var_int8 int8, )(  error, )
    InsertParameterBigserialInt64 func( var_bigserial int64, )(  error, )
    InsertParameterBigserialInt64PointerOriginal func( var_bigserial int64, )(  error, )
    InsertEntityBigserialInt64 func( var_bigserial int64, )(  error, )
    InsertEntityBigserialInt64PointerOriginal func( var_bigserial *int64, )(  error, )
    InsertParameterBigserialInt64Tx func( tx sql.Tx,  var_bigserial int64, )(  error, )
    InsertParameterBigserialInt64Rows func( var_bigserial int64, )(  int,   error, )
    InsertParameterBigserialInt64Context func( ctx context.Context,  var_bigserial int64, )(  error, )
    InsertParameterBigserialInt64Stmt func( var_bigserial int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBigserialInt64Must func( var_bigserial int64, )(  error, )
    InsertParameterBigserialInt64Embed func( var_bigserial int64, )(  error, )
    InsertParameterSerial8Int64 func( var_serial8 int64, )(  error, )
    InsertParameterSerial8Int64PointerOriginal func( var_serial8 int64, )(  error, )
    InsertEntitySerial8Int64 func( var_serial8 int64, )(  error, )
    InsertEntitySerial8Int64PointerOriginal func( var_serial8 *int64, )(  error, )
    InsertParameterSerial8Int64Tx func( tx sql.Tx,  var_serial8 int64, )(  error, )
    InsertParameterSerial8Int64Rows func( var_serial8 int64, )(  int,   error, )
    InsertParameterSerial8Int64Context func( ctx context.Context,  var_serial8 int64, )(  error, )
    InsertParameterSerial8Int64Stmt func( var_serial8 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSerial8Int64Must func( var_serial8 int64, )(  error, )
    InsertParameterSerial8Int64Embed func( var_serial8 int64, )(  error, )
    InsertParameterBitByte func( var_bit byte, )(  error, )
    InsertParameterBitBytePointerOriginal func( var_bit byte, )(  error, )
    InsertEntityBitByte func( var_bit byte, )(  error, )
    InsertEntityBitBytePointerOriginal func( var_bit *byte, )(  error, )
    InsertParameterBitByteTx func( tx sql.Tx,  var_bit byte, )(  error, )
    InsertParameterBitByteRows func( var_bit byte, )(  int,   error, )
    InsertParameterBitByteContext func( ctx context.Context,  var_bit byte, )(  error, )
    InsertParameterBitByteStmt func( var_bit byte, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBitByteMust func( var_bit byte, )(  error, )
    InsertParameterBitByteEmbed func( var_bit byte, )(  error, )
    InsertParameterBitVaryingInt64 func( var_bit_varying int64, )(  error, )
    InsertParameterBitVaryingInt64PointerOriginal func( var_bit_varying int64, )(  error, )
    InsertEntityBitVaryingInt64 func( var_bit_varying int64, )(  error, )
    InsertEntityBitVaryingInt64PointerOriginal func( var_bit_varying *int64, )(  error, )
    InsertParameterBitVaryingInt64Tx func( tx sql.Tx,  var_bit_varying int64, )(  error, )
    InsertParameterBitVaryingInt64Rows func( var_bit_varying int64, )(  int,   error, )
    InsertParameterBitVaryingInt64Context func( ctx context.Context,  var_bit_varying int64, )(  error, )
    InsertParameterBitVaryingInt64Stmt func( var_bit_varying int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBitVaryingInt64Must func( var_bit_varying int64, )(  error, )
    InsertParameterBitVaryingInt64Embed func( var_bit_varying int64, )(  error, )
    InsertParameterBooleanInt64 func( var_boolean int64, )(  error, )
    InsertParameterBooleanInt64PointerOriginal func( var_boolean int64, )(  error, )
    InsertEntityBooleanInt64 func( var_boolean int64, )(  error, )
    InsertEntityBooleanInt64PointerOriginal func( var_boolean *int64, )(  error, )
    InsertParameterBooleanInt64Tx func( tx sql.Tx,  var_boolean int64, )(  error, )
    InsertParameterBooleanInt64Rows func( var_boolean int64, )(  int,   error, )
    InsertParameterBooleanInt64Context func( ctx context.Context,  var_boolean int64, )(  error, )
    InsertParameterBooleanInt64Stmt func( var_boolean int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBooleanInt64Must func( var_boolean int64, )(  error, )
    InsertParameterBooleanInt64Embed func( var_boolean int64, )(  error, )
    InsertParameterBoolInt64 func( var_bool int64, )(  error, )
    InsertParameterBoolInt64PointerOriginal func( var_bool int64, )(  error, )
    InsertEntityBoolInt64 func( var_bool int64, )(  error, )
    InsertEntityBoolInt64PointerOriginal func( var_bool *int64, )(  error, )
    InsertParameterBoolInt64Tx func( tx sql.Tx,  var_bool int64, )(  error, )
    InsertParameterBoolInt64Rows func( var_bool int64, )(  int,   error, )
    InsertParameterBoolInt64Context func( ctx context.Context,  var_bool int64, )(  error, )
    InsertParameterBoolInt64Stmt func( var_bool int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBoolInt64Must func( var_bool int64, )(  error, )
    InsertParameterBoolInt64Embed func( var_bool int64, )(  error, )
    InsertParameterBoxInt64 func( var_box int64, )(  error, )
    InsertParameterBoxInt64PointerOriginal func( var_box int64, )(  error, )
    InsertEntityBoxInt64 func( var_box int64, )(  error, )
    InsertEntityBoxInt64PointerOriginal func( var_box *int64, )(  error, )
    InsertParameterBoxInt64Tx func( tx sql.Tx,  var_box int64, )(  error, )
    InsertParameterBoxInt64Rows func( var_box int64, )(  int,   error, )
    InsertParameterBoxInt64Context func( ctx context.Context,  var_box int64, )(  error, )
    InsertParameterBoxInt64Stmt func( var_box int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterBoxInt64Must func( var_box int64, )(  error, )
    InsertParameterBoxInt64Embed func( var_box int64, )(  error, )
    InsertParameterByteaInt64 func( var_bytea int64, )(  error, )
    InsertParameterByteaInt64PointerOriginal func( var_bytea int64, )(  error, )
    InsertEntityByteaInt64 func( var_bytea int64, )(  error, )
    InsertEntityByteaInt64PointerOriginal func( var_bytea *int64, )(  error, )
    InsertParameterByteaInt64Tx func( tx sql.Tx,  var_bytea int64, )(  error, )
    InsertParameterByteaInt64Rows func( var_bytea int64, )(  int,   error, )
    InsertParameterByteaInt64Context func( ctx context.Context,  var_bytea int64, )(  error, )
    InsertParameterByteaInt64Stmt func( var_bytea int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterByteaInt64Must func( var_bytea int64, )(  error, )
    InsertParameterByteaInt64Embed func( var_bytea int64, )(  error, )
    InsertParameterCharacterInt64 func( var_character int64, )(  error, )
    InsertParameterCharacterInt64PointerOriginal func( var_character int64, )(  error, )
    InsertEntityCharacterInt64 func( var_character int64, )(  error, )
    InsertEntityCharacterInt64PointerOriginal func( var_character *int64, )(  error, )
    InsertParameterCharacterInt64Tx func( tx sql.Tx,  var_character int64, )(  error, )
    InsertParameterCharacterInt64Rows func( var_character int64, )(  int,   error, )
    InsertParameterCharacterInt64Context func( ctx context.Context,  var_character int64, )(  error, )
    InsertParameterCharacterInt64Stmt func( var_character int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterCharacterInt64Must func( var_character int64, )(  error, )
    InsertParameterCharacterInt64Embed func( var_character int64, )(  error, )
    InsertParameterCharInt64 func( var_char int64, )(  error, )
    InsertParameterCharInt64PointerOriginal func( var_char int64, )(  error, )
    InsertEntityCharInt64 func( var_char int64, )(  error, )
    InsertEntityCharInt64PointerOriginal func( var_char *int64, )(  error, )
    InsertParameterCharInt64Tx func( tx sql.Tx,  var_char int64, )(  error, )
    InsertParameterCharInt64Rows func( var_char int64, )(  int,   error, )
    InsertParameterCharInt64Context func( ctx context.Context,  var_char int64, )(  error, )
    InsertParameterCharInt64Stmt func( var_char int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterCharInt64Must func( var_char int64, )(  error, )
    InsertParameterCharInt64Embed func( var_char int64, )(  error, )
    InsertParameterCharacterVaryingInt64 func( var_character_varying int64, )(  error, )
    InsertParameterCharacterVaryingInt64PointerOriginal func( var_character_varying int64, )(  error, )
    InsertEntityCharacterVaryingInt64 func( var_character_varying int64, )(  error, )
    InsertEntityCharacterVaryingInt64PointerOriginal func( var_character_varying *int64, )(  error, )
    InsertParameterCharacterVaryingInt64Tx func( tx sql.Tx,  var_character_varying int64, )(  error, )
    InsertParameterCharacterVaryingInt64Rows func( var_character_varying int64, )(  int,   error, )
    InsertParameterCharacterVaryingInt64Context func( ctx context.Context,  var_character_varying int64, )(  error, )
    InsertParameterCharacterVaryingInt64Stmt func( var_character_varying int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterCharacterVaryingInt64Must func( var_character_varying int64, )(  error, )
    InsertParameterCharacterVaryingInt64Embed func( var_character_varying int64, )(  error, )
    InsertParameterVarcharInt64 func( var_varchar int64, )(  error, )
    InsertParameterVarcharInt64PointerOriginal func( var_varchar int64, )(  error, )
    InsertEntityVarcharInt64 func( var_varchar int64, )(  error, )
    InsertEntityVarcharInt64PointerOriginal func( var_varchar *int64, )(  error, )
    InsertParameterVarcharInt64Tx func( tx sql.Tx,  var_varchar int64, )(  error, )
    InsertParameterVarcharInt64Rows func( var_varchar int64, )(  int,   error, )
    InsertParameterVarcharInt64Context func( ctx context.Context,  var_varchar int64, )(  error, )
    InsertParameterVarcharInt64Stmt func( var_varchar int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterVarcharInt64Must func( var_varchar int64, )(  error, )
    InsertParameterVarcharInt64Embed func( var_varchar int64, )(  error, )
    InsertParameterCidrInt64 func( var_cidr int64, )(  error, )
    InsertParameterCidrInt64PointerOriginal func( var_cidr int64, )(  error, )
    InsertEntityCidrInt64 func( var_cidr int64, )(  error, )
    InsertEntityCidrInt64PointerOriginal func( var_cidr *int64, )(  error, )
    InsertParameterCidrInt64Tx func( tx sql.Tx,  var_cidr int64, )(  error, )
    InsertParameterCidrInt64Rows func( var_cidr int64, )(  int,   error, )
    InsertParameterCidrInt64Context func( ctx context.Context,  var_cidr int64, )(  error, )
    InsertParameterCidrInt64Stmt func( var_cidr int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterCidrInt64Must func( var_cidr int64, )(  error, )
    InsertParameterCidrInt64Embed func( var_cidr int64, )(  error, )
    InsertParameterCircleInt64 func( var_circle int64, )(  error, )
    InsertParameterCircleInt64PointerOriginal func( var_circle int64, )(  error, )
    InsertEntityCircleInt64 func( var_circle int64, )(  error, )
    InsertEntityCircleInt64PointerOriginal func( var_circle *int64, )(  error, )
    InsertParameterCircleInt64Tx func( tx sql.Tx,  var_circle int64, )(  error, )
    InsertParameterCircleInt64Rows func( var_circle int64, )(  int,   error, )
    InsertParameterCircleInt64Context func( ctx context.Context,  var_circle int64, )(  error, )
    InsertParameterCircleInt64Stmt func( var_circle int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterCircleInt64Must func( var_circle int64, )(  error, )
    InsertParameterCircleInt64Embed func( var_circle int64, )(  error, )
    InsertParameterDateInt64 func( var_date int64, )(  error, )
    InsertParameterDateInt64PointerOriginal func( var_date int64, )(  error, )
    InsertEntityDateInt64 func( var_date int64, )(  error, )
    InsertEntityDateInt64PointerOriginal func( var_date *int64, )(  error, )
    InsertParameterDateInt64Tx func( tx sql.Tx,  var_date int64, )(  error, )
    InsertParameterDateInt64Rows func( var_date int64, )(  int,   error, )
    InsertParameterDateInt64Context func( ctx context.Context,  var_date int64, )(  error, )
    InsertParameterDateInt64Stmt func( var_date int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterDateInt64Must func( var_date int64, )(  error, )
    InsertParameterDateInt64Embed func( var_date int64, )(  error, )
    InsertParameterDoublePrecisionInt64 func( var_double_precision int64, )(  error, )
    InsertParameterDoublePrecisionInt64PointerOriginal func( var_double_precision int64, )(  error, )
    InsertEntityDoublePrecisionInt64 func( var_double_precision int64, )(  error, )
    InsertEntityDoublePrecisionInt64PointerOriginal func( var_double_precision *int64, )(  error, )
    InsertParameterDoublePrecisionInt64Tx func( tx sql.Tx,  var_double_precision int64, )(  error, )
    InsertParameterDoublePrecisionInt64Rows func( var_double_precision int64, )(  int,   error, )
    InsertParameterDoublePrecisionInt64Context func( ctx context.Context,  var_double_precision int64, )(  error, )
    InsertParameterDoublePrecisionInt64Stmt func( var_double_precision int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterDoublePrecisionInt64Must func( var_double_precision int64, )(  error, )
    InsertParameterDoublePrecisionInt64Embed func( var_double_precision int64, )(  error, )
    InsertParameterFloat8Int64 func( var_float8 int64, )(  error, )
    InsertParameterFloat8Int64PointerOriginal func( var_float8 int64, )(  error, )
    InsertEntityFloat8Int64 func( var_float8 int64, )(  error, )
    InsertEntityFloat8Int64PointerOriginal func( var_float8 *int64, )(  error, )
    InsertParameterFloat8Int64Tx func( tx sql.Tx,  var_float8 int64, )(  error, )
    InsertParameterFloat8Int64Rows func( var_float8 int64, )(  int,   error, )
    InsertParameterFloat8Int64Context func( ctx context.Context,  var_float8 int64, )(  error, )
    InsertParameterFloat8Int64Stmt func( var_float8 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterFloat8Int64Must func( var_float8 int64, )(  error, )
    InsertParameterFloat8Int64Embed func( var_float8 int64, )(  error, )
    InsertParameterInetInt64 func( var_inet int64, )(  error, )
    InsertParameterInetInt64PointerOriginal func( var_inet int64, )(  error, )
    InsertEntityInetInt64 func( var_inet int64, )(  error, )
    InsertEntityInetInt64PointerOriginal func( var_inet *int64, )(  error, )
    InsertParameterInetInt64Tx func( tx sql.Tx,  var_inet int64, )(  error, )
    InsertParameterInetInt64Rows func( var_inet int64, )(  int,   error, )
    InsertParameterInetInt64Context func( ctx context.Context,  var_inet int64, )(  error, )
    InsertParameterInetInt64Stmt func( var_inet int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterInetInt64Must func( var_inet int64, )(  error, )
    InsertParameterInetInt64Embed func( var_inet int64, )(  error, )
    InsertParameterIntegerInt64 func( var_integer int64, )(  error, )
    InsertParameterIntegerInt64PointerOriginal func( var_integer int64, )(  error, )
    InsertEntityIntegerInt64 func( var_integer int64, )(  error, )
    InsertEntityIntegerInt64PointerOriginal func( var_integer *int64, )(  error, )
    InsertParameterIntegerInt64Tx func( tx sql.Tx,  var_integer int64, )(  error, )
    InsertParameterIntegerInt64Rows func( var_integer int64, )(  int,   error, )
    InsertParameterIntegerInt64Context func( ctx context.Context,  var_integer int64, )(  error, )
    InsertParameterIntegerInt64Stmt func( var_integer int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterIntegerInt64Must func( var_integer int64, )(  error, )
    InsertParameterIntegerInt64Embed func( var_integer int64, )(  error, )
    InsertParameterIntInt64 func( var_int int64, )(  error, )
    InsertParameterIntInt64PointerOriginal func( var_int int64, )(  error, )
    InsertEntityIntInt64 func( var_int int64, )(  error, )
    InsertEntityIntInt64PointerOriginal func( var_int *int64, )(  error, )
    InsertParameterIntInt64Tx func( tx sql.Tx,  var_int int64, )(  error, )
    InsertParameterIntInt64Rows func( var_int int64, )(  int,   error, )
    InsertParameterIntInt64Context func( ctx context.Context,  var_int int64, )(  error, )
    InsertParameterIntInt64Stmt func( var_int int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterIntInt64Must func( var_int int64, )(  error, )
    InsertParameterIntInt64Embed func( var_int int64, )(  error, )
    InsertParameterInt4Int64 func( var_int4 int64, )(  error, )
    InsertParameterInt4Int64PointerOriginal func( var_int4 int64, )(  error, )
    InsertEntityInt4Int64 func( var_int4 int64, )(  error, )
    InsertEntityInt4Int64PointerOriginal func( var_int4 *int64, )(  error, )
    InsertParameterInt4Int64Tx func( tx sql.Tx,  var_int4 int64, )(  error, )
    InsertParameterInt4Int64Rows func( var_int4 int64, )(  int,   error, )
    InsertParameterInt4Int64Context func( ctx context.Context,  var_int4 int64, )(  error, )
    InsertParameterInt4Int64Stmt func( var_int4 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterInt4Int64Must func( var_int4 int64, )(  error, )
    InsertParameterInt4Int64Embed func( var_int4 int64, )(  error, )
    InsertParameterIntervalInt64 func( var_interval int64, )(  error, )
    InsertParameterIntervalInt64PointerOriginal func( var_interval int64, )(  error, )
    InsertEntityIntervalInt64 func( var_interval int64, )(  error, )
    InsertEntityIntervalInt64PointerOriginal func( var_interval *int64, )(  error, )
    InsertParameterIntervalInt64Tx func( tx sql.Tx,  var_interval int64, )(  error, )
    InsertParameterIntervalInt64Rows func( var_interval int64, )(  int,   error, )
    InsertParameterIntervalInt64Context func( ctx context.Context,  var_interval int64, )(  error, )
    InsertParameterIntervalInt64Stmt func( var_interval int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterIntervalInt64Must func( var_interval int64, )(  error, )
    InsertParameterIntervalInt64Embed func( var_interval int64, )(  error, )
    InsertParameterJsonInt64 func( var_json int64, )(  error, )
    InsertParameterJsonInt64PointerOriginal func( var_json int64, )(  error, )
    InsertEntityJsonInt64 func( var_json int64, )(  error, )
    InsertEntityJsonInt64PointerOriginal func( var_json *int64, )(  error, )
    InsertParameterJsonInt64Tx func( tx sql.Tx,  var_json int64, )(  error, )
    InsertParameterJsonInt64Rows func( var_json int64, )(  int,   error, )
    InsertParameterJsonInt64Context func( ctx context.Context,  var_json int64, )(  error, )
    InsertParameterJsonInt64Stmt func( var_json int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterJsonInt64Must func( var_json int64, )(  error, )
    InsertParameterJsonInt64Embed func( var_json int64, )(  error, )
    InsertParameterJsonbInt64 func( var_jsonb int64, )(  error, )
    InsertParameterJsonbInt64PointerOriginal func( var_jsonb int64, )(  error, )
    InsertEntityJsonbInt64 func( var_jsonb int64, )(  error, )
    InsertEntityJsonbInt64PointerOriginal func( var_jsonb *int64, )(  error, )
    InsertParameterJsonbInt64Tx func( tx sql.Tx,  var_jsonb int64, )(  error, )
    InsertParameterJsonbInt64Rows func( var_jsonb int64, )(  int,   error, )
    InsertParameterJsonbInt64Context func( ctx context.Context,  var_jsonb int64, )(  error, )
    InsertParameterJsonbInt64Stmt func( var_jsonb int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterJsonbInt64Must func( var_jsonb int64, )(  error, )
    InsertParameterJsonbInt64Embed func( var_jsonb int64, )(  error, )
    InsertParameterLineInt64 func( var_line int64, )(  error, )
    InsertParameterLineInt64PointerOriginal func( var_line int64, )(  error, )
    InsertEntityLineInt64 func( var_line int64, )(  error, )
    InsertEntityLineInt64PointerOriginal func( var_line *int64, )(  error, )
    InsertParameterLineInt64Tx func( tx sql.Tx,  var_line int64, )(  error, )
    InsertParameterLineInt64Rows func( var_line int64, )(  int,   error, )
    InsertParameterLineInt64Context func( ctx context.Context,  var_line int64, )(  error, )
    InsertParameterLineInt64Stmt func( var_line int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterLineInt64Must func( var_line int64, )(  error, )
    InsertParameterLineInt64Embed func( var_line int64, )(  error, )
    InsertParameterLsegInt64 func( var_lseg int64, )(  error, )
    InsertParameterLsegInt64PointerOriginal func( var_lseg int64, )(  error, )
    InsertEntityLsegInt64 func( var_lseg int64, )(  error, )
    InsertEntityLsegInt64PointerOriginal func( var_lseg *int64, )(  error, )
    InsertParameterLsegInt64Tx func( tx sql.Tx,  var_lseg int64, )(  error, )
    InsertParameterLsegInt64Rows func( var_lseg int64, )(  int,   error, )
    InsertParameterLsegInt64Context func( ctx context.Context,  var_lseg int64, )(  error, )
    InsertParameterLsegInt64Stmt func( var_lseg int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterLsegInt64Must func( var_lseg int64, )(  error, )
    InsertParameterLsegInt64Embed func( var_lseg int64, )(  error, )
    InsertParameterMacaddrInt64 func( var_macaddr int64, )(  error, )
    InsertParameterMacaddrInt64PointerOriginal func( var_macaddr int64, )(  error, )
    InsertEntityMacaddrInt64 func( var_macaddr int64, )(  error, )
    InsertEntityMacaddrInt64PointerOriginal func( var_macaddr *int64, )(  error, )
    InsertParameterMacaddrInt64Tx func( tx sql.Tx,  var_macaddr int64, )(  error, )
    InsertParameterMacaddrInt64Rows func( var_macaddr int64, )(  int,   error, )
    InsertParameterMacaddrInt64Context func( ctx context.Context,  var_macaddr int64, )(  error, )
    InsertParameterMacaddrInt64Stmt func( var_macaddr int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterMacaddrInt64Must func( var_macaddr int64, )(  error, )
    InsertParameterMacaddrInt64Embed func( var_macaddr int64, )(  error, )
    InsertParameterMacaddr8Int64 func( var_macaddr8 int64, )(  error, )
    InsertParameterMacaddr8Int64PointerOriginal func( var_macaddr8 int64, )(  error, )
    InsertEntityMacaddr8Int64 func( var_macaddr8 int64, )(  error, )
    InsertEntityMacaddr8Int64PointerOriginal func( var_macaddr8 *int64, )(  error, )
    InsertParameterMacaddr8Int64Tx func( tx sql.Tx,  var_macaddr8 int64, )(  error, )
    InsertParameterMacaddr8Int64Rows func( var_macaddr8 int64, )(  int,   error, )
    InsertParameterMacaddr8Int64Context func( ctx context.Context,  var_macaddr8 int64, )(  error, )
    InsertParameterMacaddr8Int64Stmt func( var_macaddr8 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterMacaddr8Int64Must func( var_macaddr8 int64, )(  error, )
    InsertParameterMacaddr8Int64Embed func( var_macaddr8 int64, )(  error, )
    InsertParameterMoneyInt64 func( var_money int64, )(  error, )
    InsertParameterMoneyInt64PointerOriginal func( var_money int64, )(  error, )
    InsertEntityMoneyInt64 func( var_money int64, )(  error, )
    InsertEntityMoneyInt64PointerOriginal func( var_money *int64, )(  error, )
    InsertParameterMoneyInt64Tx func( tx sql.Tx,  var_money int64, )(  error, )
    InsertParameterMoneyInt64Rows func( var_money int64, )(  int,   error, )
    InsertParameterMoneyInt64Context func( ctx context.Context,  var_money int64, )(  error, )
    InsertParameterMoneyInt64Stmt func( var_money int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterMoneyInt64Must func( var_money int64, )(  error, )
    InsertParameterMoneyInt64Embed func( var_money int64, )(  error, )
    InsertParameterNumericInt64 func( var_numeric int64, )(  error, )
    InsertParameterNumericInt64PointerOriginal func( var_numeric int64, )(  error, )
    InsertEntityNumericInt64 func( var_numeric int64, )(  error, )
    InsertEntityNumericInt64PointerOriginal func( var_numeric *int64, )(  error, )
    InsertParameterNumericInt64Tx func( tx sql.Tx,  var_numeric int64, )(  error, )
    InsertParameterNumericInt64Rows func( var_numeric int64, )(  int,   error, )
    InsertParameterNumericInt64Context func( ctx context.Context,  var_numeric int64, )(  error, )
    InsertParameterNumericInt64Stmt func( var_numeric int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterNumericInt64Must func( var_numeric int64, )(  error, )
    InsertParameterNumericInt64Embed func( var_numeric int64, )(  error, )
    InsertParameterDecimalInt64 func( var_decimal int64, )(  error, )
    InsertParameterDecimalInt64PointerOriginal func( var_decimal int64, )(  error, )
    InsertEntityDecimalInt64 func( var_decimal int64, )(  error, )
    InsertEntityDecimalInt64PointerOriginal func( var_decimal *int64, )(  error, )
    InsertParameterDecimalInt64Tx func( tx sql.Tx,  var_decimal int64, )(  error, )
    InsertParameterDecimalInt64Rows func( var_decimal int64, )(  int,   error, )
    InsertParameterDecimalInt64Context func( ctx context.Context,  var_decimal int64, )(  error, )
    InsertParameterDecimalInt64Stmt func( var_decimal int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterDecimalInt64Must func( var_decimal int64, )(  error, )
    InsertParameterDecimalInt64Embed func( var_decimal int64, )(  error, )
    InsertParameterPathInt64 func( var_path int64, )(  error, )
    InsertParameterPathInt64PointerOriginal func( var_path int64, )(  error, )
    InsertEntityPathInt64 func( var_path int64, )(  error, )
    InsertEntityPathInt64PointerOriginal func( var_path *int64, )(  error, )
    InsertParameterPathInt64Tx func( tx sql.Tx,  var_path int64, )(  error, )
    InsertParameterPathInt64Rows func( var_path int64, )(  int,   error, )
    InsertParameterPathInt64Context func( ctx context.Context,  var_path int64, )(  error, )
    InsertParameterPathInt64Stmt func( var_path int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterPathInt64Must func( var_path int64, )(  error, )
    InsertParameterPathInt64Embed func( var_path int64, )(  error, )
    InsertParameterPgLsnInt64 func( var_pg_lsn int64, )(  error, )
    InsertParameterPgLsnInt64PointerOriginal func( var_pg_lsn int64, )(  error, )
    InsertEntityPgLsnInt64 func( var_pg_lsn int64, )(  error, )
    InsertEntityPgLsnInt64PointerOriginal func( var_pg_lsn *int64, )(  error, )
    InsertParameterPgLsnInt64Tx func( tx sql.Tx,  var_pg_lsn int64, )(  error, )
    InsertParameterPgLsnInt64Rows func( var_pg_lsn int64, )(  int,   error, )
    InsertParameterPgLsnInt64Context func( ctx context.Context,  var_pg_lsn int64, )(  error, )
    InsertParameterPgLsnInt64Stmt func( var_pg_lsn int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterPgLsnInt64Must func( var_pg_lsn int64, )(  error, )
    InsertParameterPgLsnInt64Embed func( var_pg_lsn int64, )(  error, )
    InsertParameterPgSnapshotInt64 func( var_pg_snapshot int64, )(  error, )
    InsertParameterPgSnapshotInt64PointerOriginal func( var_pg_snapshot int64, )(  error, )
    InsertEntityPgSnapshotInt64 func( var_pg_snapshot int64, )(  error, )
    InsertEntityPgSnapshotInt64PointerOriginal func( var_pg_snapshot *int64, )(  error, )
    InsertParameterPgSnapshotInt64Tx func( tx sql.Tx,  var_pg_snapshot int64, )(  error, )
    InsertParameterPgSnapshotInt64Rows func( var_pg_snapshot int64, )(  int,   error, )
    InsertParameterPgSnapshotInt64Context func( ctx context.Context,  var_pg_snapshot int64, )(  error, )
    InsertParameterPgSnapshotInt64Stmt func( var_pg_snapshot int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterPgSnapshotInt64Must func( var_pg_snapshot int64, )(  error, )
    InsertParameterPgSnapshotInt64Embed func( var_pg_snapshot int64, )(  error, )
    InsertParameterPointInt64 func( var_point int64, )(  error, )
    InsertParameterPointInt64PointerOriginal func( var_point int64, )(  error, )
    InsertEntityPointInt64 func( var_point int64, )(  error, )
    InsertEntityPointInt64PointerOriginal func( var_point *int64, )(  error, )
    InsertParameterPointInt64Tx func( tx sql.Tx,  var_point int64, )(  error, )
    InsertParameterPointInt64Rows func( var_point int64, )(  int,   error, )
    InsertParameterPointInt64Context func( ctx context.Context,  var_point int64, )(  error, )
    InsertParameterPointInt64Stmt func( var_point int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterPointInt64Must func( var_point int64, )(  error, )
    InsertParameterPointInt64Embed func( var_point int64, )(  error, )
    InsertParameterPolygonInt64 func( var_polygon int64, )(  error, )
    InsertParameterPolygonInt64PointerOriginal func( var_polygon int64, )(  error, )
    InsertEntityPolygonInt64 func( var_polygon int64, )(  error, )
    InsertEntityPolygonInt64PointerOriginal func( var_polygon *int64, )(  error, )
    InsertParameterPolygonInt64Tx func( tx sql.Tx,  var_polygon int64, )(  error, )
    InsertParameterPolygonInt64Rows func( var_polygon int64, )(  int,   error, )
    InsertParameterPolygonInt64Context func( ctx context.Context,  var_polygon int64, )(  error, )
    InsertParameterPolygonInt64Stmt func( var_polygon int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterPolygonInt64Must func( var_polygon int64, )(  error, )
    InsertParameterPolygonInt64Embed func( var_polygon int64, )(  error, )
    InsertParameterRealInt64 func( var_real int64, )(  error, )
    InsertParameterRealInt64PointerOriginal func( var_real int64, )(  error, )
    InsertEntityRealInt64 func( var_real int64, )(  error, )
    InsertEntityRealInt64PointerOriginal func( var_real *int64, )(  error, )
    InsertParameterRealInt64Tx func( tx sql.Tx,  var_real int64, )(  error, )
    InsertParameterRealInt64Rows func( var_real int64, )(  int,   error, )
    InsertParameterRealInt64Context func( ctx context.Context,  var_real int64, )(  error, )
    InsertParameterRealInt64Stmt func( var_real int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterRealInt64Must func( var_real int64, )(  error, )
    InsertParameterRealInt64Embed func( var_real int64, )(  error, )
    InsertParameterFloat4Int64 func( var_float4 int64, )(  error, )
    InsertParameterFloat4Int64PointerOriginal func( var_float4 int64, )(  error, )
    InsertEntityFloat4Int64 func( var_float4 int64, )(  error, )
    InsertEntityFloat4Int64PointerOriginal func( var_float4 *int64, )(  error, )
    InsertParameterFloat4Int64Tx func( tx sql.Tx,  var_float4 int64, )(  error, )
    InsertParameterFloat4Int64Rows func( var_float4 int64, )(  int,   error, )
    InsertParameterFloat4Int64Context func( ctx context.Context,  var_float4 int64, )(  error, )
    InsertParameterFloat4Int64Stmt func( var_float4 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterFloat4Int64Must func( var_float4 int64, )(  error, )
    InsertParameterFloat4Int64Embed func( var_float4 int64, )(  error, )
    InsertParameterSmallintInt64 func( var_smallint int64, )(  error, )
    InsertParameterSmallintInt64PointerOriginal func( var_smallint int64, )(  error, )
    InsertEntitySmallintInt64 func( var_smallint int64, )(  error, )
    InsertEntitySmallintInt64PointerOriginal func( var_smallint *int64, )(  error, )
    InsertParameterSmallintInt64Tx func( tx sql.Tx,  var_smallint int64, )(  error, )
    InsertParameterSmallintInt64Rows func( var_smallint int64, )(  int,   error, )
    InsertParameterSmallintInt64Context func( ctx context.Context,  var_smallint int64, )(  error, )
    InsertParameterSmallintInt64Stmt func( var_smallint int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSmallintInt64Must func( var_smallint int64, )(  error, )
    InsertParameterSmallintInt64Embed func( var_smallint int64, )(  error, )
    InsertParameterInt2Int64 func( var_int2 int64, )(  error, )
    InsertParameterInt2Int64PointerOriginal func( var_int2 int64, )(  error, )
    InsertEntityInt2Int64 func( var_int2 int64, )(  error, )
    InsertEntityInt2Int64PointerOriginal func( var_int2 *int64, )(  error, )
    InsertParameterInt2Int64Tx func( tx sql.Tx,  var_int2 int64, )(  error, )
    InsertParameterInt2Int64Rows func( var_int2 int64, )(  int,   error, )
    InsertParameterInt2Int64Context func( ctx context.Context,  var_int2 int64, )(  error, )
    InsertParameterInt2Int64Stmt func( var_int2 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterInt2Int64Must func( var_int2 int64, )(  error, )
    InsertParameterInt2Int64Embed func( var_int2 int64, )(  error, )
    InsertParameterSmallserialInt64 func( var_smallserial int64, )(  error, )
    InsertParameterSmallserialInt64PointerOriginal func( var_smallserial int64, )(  error, )
    InsertEntitySmallserialInt64 func( var_smallserial int64, )(  error, )
    InsertEntitySmallserialInt64PointerOriginal func( var_smallserial *int64, )(  error, )
    InsertParameterSmallserialInt64Tx func( tx sql.Tx,  var_smallserial int64, )(  error, )
    InsertParameterSmallserialInt64Rows func( var_smallserial int64, )(  int,   error, )
    InsertParameterSmallserialInt64Context func( ctx context.Context,  var_smallserial int64, )(  error, )
    InsertParameterSmallserialInt64Stmt func( var_smallserial int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSmallserialInt64Must func( var_smallserial int64, )(  error, )
    InsertParameterSmallserialInt64Embed func( var_smallserial int64, )(  error, )
    InsertParameterSerial2Int64 func( var_serial2 int64, )(  error, )
    InsertParameterSerial2Int64PointerOriginal func( var_serial2 int64, )(  error, )
    InsertEntitySerial2Int64 func( var_serial2 int64, )(  error, )
    InsertEntitySerial2Int64PointerOriginal func( var_serial2 *int64, )(  error, )
    InsertParameterSerial2Int64Tx func( tx sql.Tx,  var_serial2 int64, )(  error, )
    InsertParameterSerial2Int64Rows func( var_serial2 int64, )(  int,   error, )
    InsertParameterSerial2Int64Context func( ctx context.Context,  var_serial2 int64, )(  error, )
    InsertParameterSerial2Int64Stmt func( var_serial2 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSerial2Int64Must func( var_serial2 int64, )(  error, )
    InsertParameterSerial2Int64Embed func( var_serial2 int64, )(  error, )
    InsertParameterSerialInt64 func( var_serial int64, )(  error, )
    InsertParameterSerialInt64PointerOriginal func( var_serial int64, )(  error, )
    InsertEntitySerialInt64 func( var_serial int64, )(  error, )
    InsertEntitySerialInt64PointerOriginal func( var_serial *int64, )(  error, )
    InsertParameterSerialInt64Tx func( tx sql.Tx,  var_serial int64, )(  error, )
    InsertParameterSerialInt64Rows func( var_serial int64, )(  int,   error, )
    InsertParameterSerialInt64Context func( ctx context.Context,  var_serial int64, )(  error, )
    InsertParameterSerialInt64Stmt func( var_serial int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSerialInt64Must func( var_serial int64, )(  error, )
    InsertParameterSerialInt64Embed func( var_serial int64, )(  error, )
    InsertParameterSerial4Int64 func( var_serial4 int64, )(  error, )
    InsertParameterSerial4Int64PointerOriginal func( var_serial4 int64, )(  error, )
    InsertEntitySerial4Int64 func( var_serial4 int64, )(  error, )
    InsertEntitySerial4Int64PointerOriginal func( var_serial4 *int64, )(  error, )
    InsertParameterSerial4Int64Tx func( tx sql.Tx,  var_serial4 int64, )(  error, )
    InsertParameterSerial4Int64Rows func( var_serial4 int64, )(  int,   error, )
    InsertParameterSerial4Int64Context func( ctx context.Context,  var_serial4 int64, )(  error, )
    InsertParameterSerial4Int64Stmt func( var_serial4 int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterSerial4Int64Must func( var_serial4 int64, )(  error, )
    InsertParameterSerial4Int64Embed func( var_serial4 int64, )(  error, )
    InsertParameterTextInt64 func( var_text int64, )(  error, )
    InsertParameterTextInt64PointerOriginal func( var_text int64, )(  error, )
    InsertEntityTextInt64 func( var_text int64, )(  error, )
    InsertEntityTextInt64PointerOriginal func( var_text *int64, )(  error, )
    InsertParameterTextInt64Tx func( tx sql.Tx,  var_text int64, )(  error, )
    InsertParameterTextInt64Rows func( var_text int64, )(  int,   error, )
    InsertParameterTextInt64Context func( ctx context.Context,  var_text int64, )(  error, )
    InsertParameterTextInt64Stmt func( var_text int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTextInt64Must func( var_text int64, )(  error, )
    InsertParameterTextInt64Embed func( var_text int64, )(  error, )
    InsertParameterTimeInt64 func( var_time int64, )(  error, )
    InsertParameterTimeInt64PointerOriginal func( var_time int64, )(  error, )
    InsertEntityTimeInt64 func( var_time int64, )(  error, )
    InsertEntityTimeInt64PointerOriginal func( var_time *int64, )(  error, )
    InsertParameterTimeInt64Tx func( tx sql.Tx,  var_time int64, )(  error, )
    InsertParameterTimeInt64Rows func( var_time int64, )(  int,   error, )
    InsertParameterTimeInt64Context func( ctx context.Context,  var_time int64, )(  error, )
    InsertParameterTimeInt64Stmt func( var_time int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimeInt64Must func( var_time int64, )(  error, )
    InsertParameterTimeInt64Embed func( var_time int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64 func( var_time_with_timezone int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64PointerOriginal func( var_time_with_timezone int64, )(  error, )
    InsertEntityTimeWithTimezoneInt64 func( var_time_with_timezone int64, )(  error, )
    InsertEntityTimeWithTimezoneInt64PointerOriginal func( var_time_with_timezone *int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64Tx func( tx sql.Tx,  var_time_with_timezone int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64Rows func( var_time_with_timezone int64, )(  int,   error, )
    InsertParameterTimeWithTimezoneInt64Context func( ctx context.Context,  var_time_with_timezone int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64Stmt func( var_time_with_timezone int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimeWithTimezoneInt64Must func( var_time_with_timezone int64, )(  error, )
    InsertParameterTimeWithTimezoneInt64Embed func( var_time_with_timezone int64, )(  error, )
    InsertParameterTimezInt64 func( var_timez int64, )(  error, )
    InsertParameterTimezInt64PointerOriginal func( var_timez int64, )(  error, )
    InsertEntityTimezInt64 func( var_timez int64, )(  error, )
    InsertEntityTimezInt64PointerOriginal func( var_timez *int64, )(  error, )
    InsertParameterTimezInt64Tx func( tx sql.Tx,  var_timez int64, )(  error, )
    InsertParameterTimezInt64Rows func( var_timez int64, )(  int,   error, )
    InsertParameterTimezInt64Context func( ctx context.Context,  var_timez int64, )(  error, )
    InsertParameterTimezInt64Stmt func( var_timez int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimezInt64Must func( var_timez int64, )(  error, )
    InsertParameterTimezInt64Embed func( var_timez int64, )(  error, )
    InsertParameterTimestampInt64 func( var_timestamp int64, )(  error, )
    InsertParameterTimestampInt64PointerOriginal func( var_timestamp int64, )(  error, )
    InsertEntityTimestampInt64 func( var_timestamp int64, )(  error, )
    InsertEntityTimestampInt64PointerOriginal func( var_timestamp *int64, )(  error, )
    InsertParameterTimestampInt64Tx func( tx sql.Tx,  var_timestamp int64, )(  error, )
    InsertParameterTimestampInt64Rows func( var_timestamp int64, )(  int,   error, )
    InsertParameterTimestampInt64Context func( ctx context.Context,  var_timestamp int64, )(  error, )
    InsertParameterTimestampInt64Stmt func( var_timestamp int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimestampInt64Must func( var_timestamp int64, )(  error, )
    InsertParameterTimestampInt64Embed func( var_timestamp int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64 func( var_timestamp_with_timezone int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64PointerOriginal func( var_timestamp_with_timezone int64, )(  error, )
    InsertEntityTimestampWithTimezoneInt64 func( var_timestamp_with_timezone int64, )(  error, )
    InsertEntityTimestampWithTimezoneInt64PointerOriginal func( var_timestamp_with_timezone *int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64Tx func( tx sql.Tx,  var_timestamp_with_timezone int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64Rows func( var_timestamp_with_timezone int64, )(  int,   error, )
    InsertParameterTimestampWithTimezoneInt64Context func( ctx context.Context,  var_timestamp_with_timezone int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64Stmt func( var_timestamp_with_timezone int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimestampWithTimezoneInt64Must func( var_timestamp_with_timezone int64, )(  error, )
    InsertParameterTimestampWithTimezoneInt64Embed func( var_timestamp_with_timezone int64, )(  error, )
    InsertParameterTimestampzInt64 func( var_timestampz int64, )(  error, )
    InsertParameterTimestampzInt64PointerOriginal func( var_timestampz int64, )(  error, )
    InsertEntityTimestampzInt64 func( var_timestampz int64, )(  error, )
    InsertEntityTimestampzInt64PointerOriginal func( var_timestampz *int64, )(  error, )
    InsertParameterTimestampzInt64Tx func( tx sql.Tx,  var_timestampz int64, )(  error, )
    InsertParameterTimestampzInt64Rows func( var_timestampz int64, )(  int,   error, )
    InsertParameterTimestampzInt64Context func( ctx context.Context,  var_timestampz int64, )(  error, )
    InsertParameterTimestampzInt64Stmt func( var_timestampz int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTimestampzInt64Must func( var_timestampz int64, )(  error, )
    InsertParameterTimestampzInt64Embed func( var_timestampz int64, )(  error, )
    InsertParameterTsqueryInt64 func( var_tsquery int64, )(  error, )
    InsertParameterTsqueryInt64PointerOriginal func( var_tsquery int64, )(  error, )
    InsertEntityTsqueryInt64 func( var_tsquery int64, )(  error, )
    InsertEntityTsqueryInt64PointerOriginal func( var_tsquery *int64, )(  error, )
    InsertParameterTsqueryInt64Tx func( tx sql.Tx,  var_tsquery int64, )(  error, )
    InsertParameterTsqueryInt64Rows func( var_tsquery int64, )(  int,   error, )
    InsertParameterTsqueryInt64Context func( ctx context.Context,  var_tsquery int64, )(  error, )
    InsertParameterTsqueryInt64Stmt func( var_tsquery int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTsqueryInt64Must func( var_tsquery int64, )(  error, )
    InsertParameterTsqueryInt64Embed func( var_tsquery int64, )(  error, )
    InsertParameterTsvectorInt64 func( var_tsvector int64, )(  error, )
    InsertParameterTsvectorInt64PointerOriginal func( var_tsvector int64, )(  error, )
    InsertEntityTsvectorInt64 func( var_tsvector int64, )(  error, )
    InsertEntityTsvectorInt64PointerOriginal func( var_tsvector *int64, )(  error, )
    InsertParameterTsvectorInt64Tx func( tx sql.Tx,  var_tsvector int64, )(  error, )
    InsertParameterTsvectorInt64Rows func( var_tsvector int64, )(  int,   error, )
    InsertParameterTsvectorInt64Context func( ctx context.Context,  var_tsvector int64, )(  error, )
    InsertParameterTsvectorInt64Stmt func( var_tsvector int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTsvectorInt64Must func( var_tsvector int64, )(  error, )
    InsertParameterTsvectorInt64Embed func( var_tsvector int64, )(  error, )
    InsertParameterTxidSnapshotInt64 func( var_txid_snapshot int64, )(  error, )
    InsertParameterTxidSnapshotInt64PointerOriginal func( var_txid_snapshot int64, )(  error, )
    InsertEntityTxidSnapshotInt64 func( var_txid_snapshot int64, )(  error, )
    InsertEntityTxidSnapshotInt64PointerOriginal func( var_txid_snapshot *int64, )(  error, )
    InsertParameterTxidSnapshotInt64Tx func( tx sql.Tx,  var_txid_snapshot int64, )(  error, )
    InsertParameterTxidSnapshotInt64Rows func( var_txid_snapshot int64, )(  int,   error, )
    InsertParameterTxidSnapshotInt64Context func( ctx context.Context,  var_txid_snapshot int64, )(  error, )
    InsertParameterTxidSnapshotInt64Stmt func( var_txid_snapshot int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterTxidSnapshotInt64Must func( var_txid_snapshot int64, )(  error, )
    InsertParameterTxidSnapshotInt64Embed func( var_txid_snapshot int64, )(  error, )
    InsertParameterUuidInt64 func( var_uuid int64, )(  error, )
    InsertParameterUuidInt64PointerOriginal func( var_uuid int64, )(  error, )
    InsertEntityUuidInt64 func( var_uuid int64, )(  error, )
    InsertEntityUuidInt64PointerOriginal func( var_uuid *int64, )(  error, )
    InsertParameterUuidInt64Tx func( tx sql.Tx,  var_uuid int64, )(  error, )
    InsertParameterUuidInt64Rows func( var_uuid int64, )(  int,   error, )
    InsertParameterUuidInt64Context func( ctx context.Context,  var_uuid int64, )(  error, )
    InsertParameterUuidInt64Stmt func( var_uuid int64, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterUuidInt64Must func( var_uuid int64, )(  error, )
    InsertParameterUuidInt64Embed func( var_uuid int64, )(  error, )
    InsertParameterXmlString func( var_xml string, )(  error, )
    InsertParameterXmlStringPointerOriginal func( var_xml string, )(  error, )
    InsertEntityXmlString func( var_xml string, )(  error, )
    InsertEntityXmlStringPointerOriginal func( var_xml *string, )(  error, )
    InsertParameterXmlStringTx func( tx sql.Tx,  var_xml string, )(  error, )
    InsertParameterXmlStringRows func( var_xml string, )(  int,   error, )
    InsertParameterXmlStringContext func( ctx context.Context,  var_xml string, )(  error, )
    InsertParameterXmlStringStmt func( var_xml string, )( stmt *gobatis.Stmt,  err error, )
    InsertParameterXmlStringMust func( var_xml string, )(  error, )
    InsertParameterXmlStringEmbed func( var_xml string, )(  error, )
}